# Generated by Django 5.2.6 on 2025-11-17 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_order_name_order_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='surname',
            field=models.CharField(default='', max_length=120),
        ),
    ]
