# Generated by Django 5.2.6 on 2025-11-18 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_discount_product_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount',
        ),
    ]
