# Generated by Django 5.2.8 on 2025-11-30 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_order_total'),
        ('store', '0006_product_is_new'),
    ]

    operations = [
    ]
